name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:      # lets you run it manually

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: chandini1727
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake SVG to the `output` branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
