name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: chandini1727
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
